# Generated by Django 4.0.4 on 2022-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeFamiliar', models.IntegerField(max_length=50)),
                ('nombreYapellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.CharField(max_length=50)),
            ],
        ),
    ]
